config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :todo, presence: true,
            length: { minimum: 5 }
  validates :description, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end
  def show
    @todo = Todo.find(params[:id])
  end
  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end

  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to @todo
    else
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:todo,:description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbaProject1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Article</h1>

<%= form_with(model: @todo, local: true) do |form| %>

  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todo.errors.count, "error") %> prohibited
        this To Do from being saved:
      </h2>
      <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :todo %><br>
    <%= form.text_field :todo %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Your To Do List</h1>

<table>
  <tr>
    <th>To Do</th>
    <th>Description</th>
    <th></th>
  </tr>

  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.todo %></td>
      <td><%= todo.description %></td>
      <td><%= link_to 'Show', todo_path(todo) %></td>
      <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
      <td><%= link_to 'Destroy', todo_path(todo),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>New To Do</h1>

<% if @todo.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@todo.errors.count, "error") %> prohibited
      this To Do from being saved:
    </h2>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with scope: :todo, url: todos_path, local: true do |form| %>
  <p>
    <%= form.label :todo %><br>
    <%= form.text_field :todo %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p>
  <strong>TO DO:</strong>
  <%= @todo.todo %>
</p>

<p>
  <strong>DESCRIPTION:</strong>
  <%= @todo.description %>
</p>
<td><%= link_to 'Edit', edit_todo_path %></td>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>